name: Scandalorian Ingest Build

on:
  push:
    branches:
      - master

jobs:
  ingest-build-arm:
    runs-on: ubuntu-latest
    name: Build arm version of ingest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/scandalorian-ingest:arm --target=arm --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/scandalorian-ingest:arm
  ingest-build-arm64:
    runs-on: ubuntu-latest
    name: Build arm64 version of ingest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm64
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/scandalorian-ingest:arm64 --target=arm64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/scandalorian-ingest:arm64
  ingest-build-amd64:
    runs-on: ubuntu-latest
    name: Build amd64 version of ingest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build AMD64
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/scandalorian-ingest:amd64 --target=amd64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/scandalorian-ingest:amd64
  ingest-build-manifest:
    runs-on: ubuntu-latest
    name: Collect manifest and push
    needs: ["ingest-build-arm", "ingest-build-arm64", "ingest-build-amd64"]
    steps:
      - uses: actions/checkout@v2
          
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Manifest
        run: |
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create charlesdburton/scandalorian-ingest:${{ github.sha }} \
          charlesdburton/scandalorian-ingest:amd64 \
          charlesdburton/scandalorian-ingest:arm \
          charlesdburton/scandalorian-ingest:arm64 
      - name: Annotate Arm
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm charlesdburton/scandalorian-ingest:${{ github.sha }} charlesdburton/scandalorian-ingest:arm
      - name: Annotate Arm64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm64 charlesdburton/scandalorian-ingest:${{ github.sha }} charlesdburton/scandalorian-ingest:arm64
      - name: Annotate AMD64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch amd64 charlesdburton/scandalorian-ingest:${{ github.sha }} charlesdburton/scandalorian-ingest:amd64
      - name: Push Manifest
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push charlesdburton/scandalorian-ingest:${{ github.sha }}